### PR TITLE
Fix printf warning for 64 bit systems

### PR DESCRIPTION
**Pull request by OlegHahm**

### CODE REVIEW

**Comment by boaks** [comment]
Thanks for your contribution.

For open source projects of the Eclipse Foundation some rules for such contributions need to be obeyed to ensure, that others are able to use it with the Eclipse License (EPL 1.0).

Did you read the [CONTRIBUTING](CONTRIBUTING.md) guidance?

This PR was prepared by two persons. Unfortunately, this is not the standard way, because it introduces some legal uncertainty and therefore requires a CQ (contribution questionnaire, request filled by the project to be proven by eclipse legal.) It would require a ECA by all involved persons.

For now, no one, neither the author nor the committer has signed a ECA, right?

(To be frank, for two line, please clarify, which one of you want to contribute it. Though I'm not longer able to spend more than 4h a week for Californium and tinydtls together, a CQ for 2 lines isn't that productive. I don't make the rules, that the Eclipse Foundation, I have just to ensure, that this rules are applied.)

**Comment by boaks** [comment]
> I've commited to Eclipse projects before and have signed the ECA.

I used the eclipse tool to verify the record for the e-mail address, oleg@riot-os.org, used in the commit. According to that record, there is no ECA for that e-mail address.

**Comment by OlegHahm** [comment]
Probably used a different email there. @fzi-haxel if you don't have the ECA signed - would you be fine if I amend the commit (using the correct email address)?

**Comment by boaks** [comment]
I try to write a e-mail to the author ... we will see.

**Comment by boaks** [comment]
According the e-mail exchange, I extended this fix to zephyr, see PR #217

**Pull request closed without merging**
