### PR TITLE
dtls.c: Fix cipher suite and compression method decoding.

### PR DESCRIPTION
**Pull request by boaks**
Issue #100

Ensure, that at least one cipher suite and one compression method is
present. Add skip for left compression methods.

Signed-off-by: Achim Kraus <achim.kraus@bosch.io>

### CODE REVIEW

**Comment by boaks** [comment]
FMPOV,  low hanging fruit for the time, I prepare a alternative for PR #88.

**Comment by obgm** [comment]
Thanks, looks good to me.
Can you please rephrase the commit message:
```
dtls.c: fix cipher-suites and compression methods decoding

Ensure that at least one cipher suite and one compression method is
present. Skip remaining compression methods.

Fixes: Issue #100
Signed-off-by: Achim Kraus <achim.kraus@bosch.io>
```

**Comment by boaks** [comment]
Done.

**Comment by obgm** [comment]
Great, thanks!

**Pull request merged**
