### PR TITLE
Support zephyr.

### PR DESCRIPTION
**Pull request by boaks**
Add initial support for zephyr.

Signed-off-by: Achim Kraus <achim.kraus@cloudcoap.net>

### CODE REVIEW

**Comment by obgm** [comment]
Thank you very much for porting tinydtls to another platform. Given that I have installed the zephyrproject files and SDK and being able to build and flash the blinky project: How do I now test the tinydtls build with zephyr?

**Comment by boaks** [comment]
Unfortunately, I'm more or less only a newbie for zephyr. 
I already raise some questions about [best practice](https://github.com/zephyrproject-rtos/zephyr/discussions/47131) in zephyr but the answers are still pending. With that, it's for now not too easy to document, how to use it from scratch. That depends more on zephyr and the assumed know-how of an zephyr user.
 
Never the less, I also published a simple demo client, [Zephyr - CoAP/DTLS CID -Thingy:91](https://github.com/boaks/zephyr-coaps-client), which comes with some documentation how to setup and build it. The project currently supports only one device, a real one ;-). It may be extended in the future to at least support the qemu_x86 (Emulator).

If I'm more common with zephyr, I will also add some basic setup & build information. Maybe it's possible to add support for qemu_x86 even to the tinydtls examples. Until that, we can simply leave this PR open, if you prefer.

**Comment by obgm** [comment]
OK, no problem. I do not think that this PR breaks the existing code, therefore merging should not do much harm. Let me have a final look...

**Comment by obgm** [comment]
`west build -b thingy91_nrf9160_ns` for [zephyr-coaps-client](https://github.com/boaks/zephyr-coaps-client) with a tinydtls that is replaced with this PR's version, I get a couple of cmake warnings (see below). Otherwise, everything works as expected.

```
CMake Warning (dev) at /tmp/zep/zephyr-coaps-client/modules/lib/tinydtls/CMakeLists.txt:28 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_SHARED_LIBS'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /tmp/zep/zephyr-coaps-client/modules/lib/tinydtls/CMakeLists.txt:41 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'DTLS_ECC'.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /tmp/zep/zephyr-coaps-client/modules/lib/tinydtls/CMakeLists.txt:42 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'DTLS_PSK'.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by boaks** [comment]
Yes, I get them as well ;-). 
At least since updating from "NCS-1.9.1" to "NCS-2.0.0", but before there have also been some warnings. 
I postponed the "cleanup" in favor for other "pending jobs".
(I'm not only "no zephyr" expert, I'm also not that common with "cmake" ;-) ).

**Comment by boaks** [comment]
Great!

**Comment by boaks** [comment]
In the meantime I spend some time in the above Warnings:

> CMake Warning (dev) at /tmp/zep/zephyr-coaps-client/modules/lib/tinydtls/CMakeLists.txt:28 (option):
>   Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
>   --help-policy CMP0077" for policy details.  Use the cmake_policy command to
>   set the policy and suppress this warning.

The background is the cmake option, which could be set by cmake, vs. cmake variable, which are set by the zephyr Kconfig system. The fix/work-around is to add a:

```
if(NOT ZEPHYR_BASE)
   # that's provided by the zephyr build system
   option(BUILD_SHARED_LIBS "Link using shared libs" OFF)
endif()

if(NOT ZEPHYR_BASE)
   # that's provided by Kconfig from zephyr build system
   option(DTLS_ECC "disable/enable support for TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8" ON )
endif()
```

I will try to fix that after PR #126 is merged.

**Pull request merged**
