### PR TITLE
ci: add basic CI workflow

### PR DESCRIPTION
**Pull request by JKRhb**
This PR makes a proposal for a very basic CI workflow, which makes sure the project can be built for Linux using both autotools and CMake. Other platforms, including macOS and Windows, and/or build configurations (like RIOT or Zephyr) could be added in follow-up PRs.

### CODE REVIEW

**Comment by JKRhb** [comment]
Update: Added a job for macOS in the latest commit. I assume for them to run, they need to be enabled explicitly in the repository settings?

**Comment by obgm** [comment]
Looks like a good starting point. Can you please
1. add the develop branch and
2. squash the commits.

**Comment by JKRhb** [comment]
>     2. squash the commits.

Done :)

>    1. add the develop branch

I changed the target branch to `develop`, did you mean that? Or should the `develop` branch be merged into this one?

**Comment by JKRhb** [comment]
Ah, sorry, I've got it now – I'll update the PR in a moment :)

**Comment by JKRhb** [comment]
I added the `develop` branch in 44e09ec5347bd9da835921b7aabcc006252415ac, the two commits could also be squashed into one if you like.

**Comment by obgm** [comment]
> I added the `develop` branch in [44e09ec](https://github.com/eclipse/tinydtls/commit/44e09ec5347bd9da835921b7aabcc006252415ac), 

Thanks, that was the intention of my comment.

> the two commits could also be squashed into one if you like.

Yes, please.

**Comment by JKRhb** [comment]
> > the two commits could also be squashed into one if you like.
> 
> Yes, please.

Done :)

**Comment by obgm** [comment]
I will merge this into develop to check if the CI works out of the box (possibly we need to make the helpdesk switch on GH workflows).

**Comment by mrdeep1** [comment]
See #67 which refers to [Jenkins CI](https://ci.eclipse.org/tinydtls/).

**Comment by obgm** [comment]
Yeah, I was hoping that things are more like 2020's by now. Checking...

**Comment by obgm** [comment]
In fact, PR #67 is more elaborated. Let's try to take this as trigger for doing the GH CI workflow.

**Comment by mrdeep1** [comment]
#67 uses actions/checkout@v2 instead of actions/checkout@v3 and still refers to master.

**Comment by obgm** [comment]
Here is the [request](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1631)

**Comment by obgm** [comment]
> Here is the [request](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1631)

Funny: It should already have worked. No idea, why it did not. @JKRhb are you sure that the yaml does not have to be in `.github/workflows/` ?

**Comment by obgm** [comment]
> My #67 (updated) yaml works and triggers a workflow action, but that is in my repository.

Can you just revive it?

**Comment by mrdeep1** [comment]
I have had to create a new PR.  Action seems not to have triggered though.

**Comment by obgm** [comment]
@JKRhb @mrdeep1 Thanks for making this work. I think we should take PR #163 as a starting point and add, e.g., clang, cmake, and potentially macos builds there.

**Comment by mrdeep1** [comment]
I have added in the cmake for linux and macos into #163 and pushed the code.  clang to follow.

**Comment by obgm** [comment]
@JKRhb anything missing in PR #163? Otherwise, I think we can close this PR as superseded.

**Comment by JKRhb** [comment]
> > Here is the [request](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1631)
> 
> Funny: It should already have worked. No idea, why it did not. @JKRhb are you sure that the yaml does not have to be in `.github/workflows/` ?

Oh, sorry, that was actually a mistake 😅 Thanks for fixing it and incorporating this PR in #163 :)

> @JKRhb anything missing in PR https://github.com/eclipse/tinydtls/pull/163? Otherwise, I think we can close this PR as superseded.

#163 looks good, thanks @mrdeep1 :) Closing this PR as superseded.

**Pull request closed without merging**
